### ISSUE TITLE
VMs don't join the mesh if they don't belong to the fleet GCP project

### ISSUE THREAD

**Issue by claudioscalzo** [GoogleCloudPlatform/anthos-service-mesh-packages#1183]
When installing ASM with VM support, it is currently possible to add GCE VMs to the mesh by exploiting the `service-proxy-agent` package, which allows the Envoy proxy on the VM to authenticate and join the mesh.

However, when the GCE VM belongs to a GCP project different from the one hosting the mesh, the join fails with an error:

```
Prepared federated token request for aud "identitynamespace:<mesh_project_id>.svc.id.goog:<creds_idp_id>@google@<vm_namespace>
fetched federated token
access token response does not have access token
"error": {
  "code": 403,
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
}
```

As VM support is often used to support legacy applications, adding VMs belonging to different projects could be a critical use case for many users. Can you suggest a possible solution or workaround for this?

**Comment by zerobfd** [comment]
It took me awhile to dig around and try to find out since it appears like that preview option dropped off of Cloud docs in version 1.11. Unfortunately the answer now is no, it doesn't seem possible to add VMs from a separate project to the same mesh.

If you go through Cloud support channels it might be possible to find some other way to solve the high-level problem outside of ASM, but I can't think of any way that the config/tools in this repo could help.
