### ISSUE TITLE
1.12.7-asm.2-distroless image for istio-proxy missing on gcr.io

### ISSUE THREAD

**Issue by unlimitedbits** [GoogleCloudPlatform/anthos-service-mesh-packages#1233]
Hello,

today we wanted to begin upgrading our clusters to 1.12.7-asm.2.
Unfortunately, the distroless image is missing for this version (1.12.7-asm.2-distroless) and we cannot upgrade our istio-ingressgateway and proxy sidecars.

```bash
containerStatuses:
  - image: gcr.io/gke-release/asm/proxyv2:1.12.7-asm.2-distroless
    imageID: ""
    lastState: {}
    name: istio-proxy
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "gcr.io/gke-release/asm/proxyv2:1.12.7-asm.2-distroless"
        reason: ImagePullBackOff
```

**Comment by zerobfd** [comment]
This should be fixed now.

In general, issues that don't specifically have to do with `asmcli` get triaged faster if you go through Cloud support instead of GitHub. We'll always pass along issues when we can, but that's relying on one or two people checking e-mail notifications from GitHub to notice.
