### ISSUE TITLE
asmcli attempts to download a tagged version of asm that doesn't appear to exist

### ISSUE THREAD

**Issue by ps185367** [GoogleCloudPlatform/anthos-service-mesh-packages#1297]
When attempting to install asm version 1.13.4-4, I'm receiving the following error:
```shell
asmcli: Downloading ASM kpt package...

fetching package /asm from https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages to asm

asmcli: [WARNING]: Failed, retrying...(1 of 3)

fetching package /asm from https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages to asm

asmcli: [WARNING]: Failed, retrying...(2 of 3)

fetching package /asm from https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages to asm

asmcli: [WARNING]: Failed, retrying...(3 of 3)

asmcli: [WARNING]: Command 'kpt pkg get --auto-set=false https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@1.13.4-asm.4+config4 asm' failed.

script returned exit code 1
```

I tried to verify that the tag exists but I'm coming up empty. As far as i can tell, the latest config for this particular version of asm is [1.13.4-asm.4+config2](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/releases/tag/1.13.4-asm.4+config2). Looking through the asmcli documentation, I can't seem to find how to override this behavior and attempt to download config2 instead of the seemingly non-existent config4

**Comment by zerobfd** [comment]
That's weird, I'm not sure how that could happen. If you need a quick workaround you can just edit around line 40 to change the config version to whatever you need.

When/how did you download asmcli? Is that version important to use, or can you use the latest 1.13 version? I'll look into the release logs and see if I can find anything.

**Comment by zerobfd** [comment]
Looking at https://storage.googleapis.com/csm-artifacts/asm/ASMCLI_VERSIONS it doesn't look like we ever released `asmcli` for 1.13.4-4config4. If you're following some documentation could you link it so I can make sure there isn't a typo somewhere?

**Comment by ps185367** [comment]
Hey @zerobfd  thanks for the quick response. I was just following the standard google documentation on this. I didn't try to specify the config at any point and this command had been working until recently. I had assumed the config # was being chosen by asmcli incorrectly. The pipeline is downloading asmcli straight from the source and running it. Here's the full cmds that are being run


```shell
curl https://storage.googleapis.com/csm-artifacts/asm/asmcli_${details.asmMajor}.${details.asmMinor} > asmcli && chmod +x asmcli
mkdir asm

MAJOR=${details.asmMajor} MINOR=${details.asmMinor} POINT=${details.asmPoint} REV=${details.asmRev} ./asmcli install \
--project_id ${projectKey} \
--cluster_name ${cluster} \
--cluster_location ${details.region} \
--enable_all \
--enable-registration \
--output_dir asm \
--option cloud-tracing \
--option legacy-default-egressgateway \
--option envoy-access-log \
--option multicluster \
--option iap-operator \
--custom_overlay kustomize/asm-base/asm-overlay-istio-svc.yaml \
--custom_overlay kustomize/asm-base/asm-overlay-telemetry.yaml
```

**Comment by zerobfd** [comment]
Ahha, I see the problem.

We publish `asmcli` a few different ways. The very latest version always goes to a bare `asmcli`. The latest patch version for each minor version goes to `asmcli_${MAJOR}.${MINOR}`. Finally we publish the full version string for customers who want to pin to a specific version of asmcli. (You can see all of them in the url in my previous comment.)

Since you're specifying major and minor version, you get the latest version of the 1.13 tool which is currently pointing to a 1.13.5 version with a config version of 4. Then, when you run the command, you're overriding all of the MAJOR/MINOR/POINT/REV with new versions, but not the CONFIG_VER which stays pointing to 4. But that's not a valid config version for the ASM version that you specified.

Generally you shouldn't need to specify any environment variables when you run the tool. If you want to pin to a specific version, I would just download the exact tool from the ASMCLI_VERSIONS file instead of overriding variables. (The file *should* be semver sortable if you want to try anything fancy but no guarantees.)

**Comment by ps185367** [comment]
Ahhh that makes sense. Thanks for walking me through it. I was able to override the behavior by specifying CONFIG_VER like I did MAJOR/MINOR/POINT/REV. Will adjust to use your recommendations. Thanks again.
