### ISSUE TITLE
Creating internal ingress gateway

### ISSUE THREAD

**Issue by paulwilljones** [GoogleCloudPlatform/anthos-service-mesh-packages#168]
Is there a way of setting the ingress gateway component load balancer type in `istio-operator.yaml` to 'internal' when using `asm-patch` and `kpt`?

I see it's set up in `asm/istio/options/internal-load-balancer.yaml`.

How does one deploy this following [these](https://cloud.google.com/service-mesh/docs/gke-install-asm#preparing_resource_configuration_files) installation instructions?

**Comment by paulwilljones** [comment]
We're also using the Terraform submodule to install ASM. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/v9.4.0/modules/asm

**Comment by zerobfd** [comment]
If you're asking whether there's a supported, stable way of doing this with the version of ASM installed by that Terraform module, then I'm pretty sure the answer is "no."

Unofficially, if you're feeling adventurous and willing to do some code surgery, it looks like it might be possible to
* take the asm/istio/options/internal-load-balancer.yaml from the master branch and 
* add it as a kustomize patch here: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/tree/release-1.5-asm/asm-patch/patches
* before this line in the TF module: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v9.4.0/modules/asm/scripts/install_asm.sh#L56

Also unofficially, if we go by the instructions you linked which installs with istioctl instead of gcloud, you could do something similar by passing the `internal-load-balancer.yaml` file as another -f argument, e.g. `istioctl install -f istio-operator.yaml -f internal-load-balancer.yaml`

Both of these come with the caveats that 1) neither I nor anyone else I know has tried this, 2) it's completely unsupported, and 3) even if it works once there's no guarantee it will after that.

If you want something supported, I would either wait until 1.7 is released with more flexible configuration options, or put in a feature request on the terraform-google-kubernetes-engine repo to enable using an internal load balancer.

**Comment by zerobfd** [comment]
Closing this for now, feel free to re-open if there's something else we can help with here.
