### ISSUE TITLE
install_asm script is failing on Mac

### ISSUE THREAD

**Issue by imrannayer** [GoogleCloudPlatform/anthos-service-mesh-packages#258]
install_asm script is failing on mac with the following error when I use `--output_dir` option. Is there any plan for making this script available for Mac?

```
nstall_asm: Setting up necessary files...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by zerobfd** [comment]
Yes, at least Macs with modern versions of bash. I didn't know that the BSD version of readlink didn't use -f the same way, but someone identified a fix today so it's going in asap.

I can't promise compatibility forever since right now I don't have a way to test on a Mac, but it's a goal and we'll definitely fix issues as they come up.

**Comment by na-ga** [comment]
I have the BSD version of stat installed on my Mac, but the -f in the BSD version of stat is a formatting option, so it doesn't return the absolute path as expected. what about using greadlink or realpath on a Mac? If using greadlink, we need to install coreutils.

````
$ uname -a
Darwin 60-77490 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 20204

$ stat -f . /asm_build_package
. /asm_build_package

$ readlink -f . /asm_build_package
readlink: invalid option -- f
Usage: readlink [-n] [file ...] . .

$ greadlink -f . /asm_build_package
/Users/na-ga/asm/asm_build_package

. $ realpath . /asm_build_package
/Users/na-ga/asm/asm_build_package
```
