### ISSUE TITLE
question: how to use install_asm to upgrade exiting installation?

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/anthos-service-mesh-packages#306]
i've used the install_asm with default approach (gcp profile)

now if i want to add eagressgateway or other options that do not exist on asm/istio/options files (such as multiple ingresses), how can i achieve that?
can i rerun npm_install with custom overlay?
it looks like it will reinstall everything and not upgrade

**Comment by zerobfd** [comment]
Right now, install_asm only performs the initial installation. In order to make changes post-install you can use the `istioctl` binary that corresponds to the ASM version to apply them. See e.g. https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway for an example.

We're working on the ability to use install_asm in order to install as well as manage/reconcile ASM, but right now it's not possible.

If you know at install time that you'd like multiple options, you can also create them manually and specify them with the --custom_overlay option.

**Comment by lechen26** [comment]
Thanks @zerobfd ,
based on  https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway , if i  do use the istioctl install i will need to use the same flags that install_asm used no?
does it mean it will do fresh install?
once i've tried something similar , i saw fresh install of istio along with the istio-asm.

**Comment by zerobfd** [comment]
Yes, you do have to use the same options. When you run `install_asm` it should save the generated configuration to a file to use later for exactly this circumstance. If you need to generate it, you should be able to get the same thing by re-running the installation with the `--print-config` option and it will dump the config to stdout.

**Comment by zerobfd** [comment]
Closing for now, feel free to re-open or file another issue whenever necessary.
