### ISSUE TITLE
When --managed is enabled, can_modify_gcp_iam_roles always returns true

### ISSUE THREAD

**Issue by cagataygurturk** [GoogleCloudPlatform/anthos-service-mesh-packages#419]
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/3b87e4e176790f1eafdb033726b435a953ea5e7f/scripts/asm-installer/install_asm#L427-L431

This makes impossible to run the script if the user prefers setting IAM rules on her own.

Modifying the function as follows solves the issue.

```
can_modify_gcp_iam_roles() {
  if [[ "${ENABLE_ALL}" -eq 0 && "${ENABLE_GCP_IAM_ROLES}" -eq 0 ]] || \
    ! can_modify_at_all; then false; fi
}
```

**Comment by zerobfd** [comment]
Thank you for the issues and PRs!

Generally, the tool is far too generous with permissions. Someone wrote down a list at some point and it got documented, and going through and finding the minimum permissions for each case hasn't been a priority until recently. (It is getting worked on! If you're interested I can give you the permissions for a custom role which I think should be pretty close.)

Specifically, this is required for preview of the managed control plane, because part of the permissions have to be granted client-side. This was one of the UX shortcuts that got taken to get the preview out sooner.
