### ISSUE TITLE
validate-asm errors and multiple nodepools

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/anthos-service-mesh-packages#66]
Hi,

I have a regional GKE cluster with multiple nodepools and while validating asm install using `kpt fn source ${BASE_DIR} | kpt fn run --image gcr.io/kustomize-functions/validate-asm:v0.1.0` produces the following errors/warnings:

```
2 warning(s) occurred:
        * Warning - spec.nodeCount is 2 in ContainerNodePool asm-node-pool (all.yaml [8]). ASM requires at least four nodes. If you need to add nodes, see https://bit.ly/2RnVL2T
        * Warning - spec.initialNodeCount missing in ContainerNodePool default-pool (all.yaml [9])

2 error(s) occurred:
        * Error - unsupported machine type: n1-standard-1 in ContainerCluster foo-cluster (all.yaml [7]). The minimum machine type is n1-standard-4, which has four vCPUs. If the machine type for your cluster doesn't have at least four vCPUs, change the machine type as described here https://bit.ly/2V0KPdu
        * Error - unsupported machine type: n1-standard-1 in ContainerNodePool default-pool (all.yaml [9]). The minimum machine type is n1-standard-4, which has four vCPUs. If the machine type for your cluster doesn't have at least four vCPUs, change the machine type as described here https://bit.ly/2V0KPdu
```

My `default-pool` has 0 nodes and `asm-node-pool` has 6 (2 per zone) of type `e2-standard-4`. Based on the documentation my understanding was that the requirement was 

- At least four nodes.
- The minimum machine type is e2-standard-4

Any insight into these errors or if I am missing something would be great!

**Comment by elfinhe** [comment]
cc: @nan-yu can you help take a look?

**Comment by nan-yu** [comment]
Thanks for bringing this up. The current validate function checks each individual nodepool separately. We need to update the function to check the aggregated node counts from multiple nodepools.

A question for @elfinhe , does ASM prevent installation on nodepools that don't meet the minimum machine type?
For example, I have nodepool-A with 2 nodes of type n1-standard-1, and nodepool-B with 4 nodes of e2-standard-4. Will ASM pick nodes from nodepool-A?

**Comment by elfinhe** [comment]
ASM only has a soft requirement (recommendation) on nodepools. As a checker in validator, I'd suggest we do not check static CPU numbers (because we've improved istio in the recent versions, users can always overwrite the CPU reqs to a lower number, AFAIK, ASD only gives Istiod 50m CPU, it works well). 

We can update the nodepool check from Error to Warning. If node type only has 1 vCPU, we give a warning saying. "Warning. Machine type of nodepool <xxx> is <>, with only 1 vCPU. By default, Istiod requests 1 vCPU to be scalable for 2000 sidecars. Please make sure you reduce the CPU requests of Istiod before installing. See more: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/."

**Comment by nan-yu** [comment]
@elfinhe sounds good.
To summarize, we'll make the following changes in the validate function:
- Move the machineType check failure from Error to Warning
- For multiple nodepools
   - Aggregate the nodeCount and return a warning only when the total node count from all nodepools is less than 4.
   - Return a warning if one of the nodepool doesn't meet the minimum machineType requirement because ASM may be installed on that nodepool.

**Comment by elfinhe** [comment]
exactly, thanks Nan.
