### ISSUE TITLE
Kptfile version upgrade

### ISSUE THREAD

**Issue by samprit** [GoogleCloudPlatform/anthos-service-mesh-packages#834]
I'm getting old version error when trying to fetch asm.

```
Error: Kptfile at "https:/github.com/GoogleCloudPlatform/anthos-service-mesh-packages/asm@staging-1.8-asm" has an old version ("v1alpha1") of the Kptfile schema.
Please update the package to the latest format by following https://kpt.dev/installation/migration. 
```

**Comment by zerobfd** [comment]
Kpt released a breaking change recently that makes older config packages incompatible. If you use `install_asm` then this is handled for you, otherwise you need to manually download a pre v1 version of `kpt` to use. See https://cloud.google.com/service-mesh/docs/environment-setup#use-linux for steps.
